import { Recommended, columns } from "./columns";
import { DataTable } from "./data-table";

const getData = async (): Promise<Recommended[]> => {
  return [
      {
    id: "1",
    tanggal: "2024-02-15",
    judul: "Jalan depan SP Batu Aji rusak parah",
    deskripsi: "Jalan depan SP Batu Aji rusak banget, bikin motor bisa jatuh.",
    cuaca: "hujan",
    kerusakan: "80%",
    lokasi: "Jl. Letjend Suprapto, Tembesi, Kec. Sagulung, Kota Batam",
    status: "selesai",
  },
  {
    id: "2",
    tanggal: "2024-03-20",
    judul: "Perbaikan jalan di Batam lambat banget",
    deskripsi: "Susah ya perbaikan jalan di Batam, kayak nunggu keajaiban.",
    cuaca: "cerah",
    kerusakan: "60%",
    lokasi: "Jl. Letjend Suprapto, Tembesi, Kec. Sagulung, Kota Batam",
    status: "disembunyikan",
  },
  {
    id: "3",
    tanggal: "2024-11-03",
    judul: "Lampu jalan padam di Bengkong",
    deskripsi: "Lampu jalan di Bengkong udah seminggu mati, rawan kecelakaan.",
    cuaca: "cerah",
    kerusakan: "40%",
    lokasi: "Jl. Golden Prawn 56, Tj. Buntung, Kec. Bengkong, Kota Batam, Kepulauan Riau 29444", 
    status: "selesai",
  },
  {
    id: "4",
    tanggal: "2025-01-10",
    judul: "Trotoar rusak dan tidak layak di Batam Center",
    deskripsi: "Trotoar di Batam Center bikin pejalan kaki bingung, udah kayak arena offroad.",
    cuaca: "cerah",
    kerusakan: "60%",
    lokasi: "Tlk. Tering, Kec. Batam Kota, Kota Batam",
    status: "selesai",
  },
  {
    id: "5",
    tanggal: "2025-04-21",
    judul: "Ada yang mencuri besi jembatan di Sei Beduk",
    deskripsi: "Besi jembatan di Sei Beduk hilang, siapa sih tolol yang mikir ini ide bagus?",
    cuaca: "hujan",
    kerusakan: "100%",
    lokasi: "Jl. Diponegoro, Tj. Riau, Kec. Sekupang, Kota Batam, Kepulauan Riau 29424",
    status: "disembunyikan",
  },
  {
    id: "6",
    tanggal: "2024-12-05",
    judul: "Genangan air di jalan utama Batam",
    deskripsi: "Kalau hujan sedikit aja langsung banjir, pemerintah tidur apa?",
    cuaca: "hujan",
    kerusakan: "80%",
    lokasi: "Jl. Letjend Suprapto, Tembesi, Kec. Sagulung, Kota Batam",
    status: "disembunyikan",
  },
  {
    id: "7",
    tanggal: "2024-07-19",
    judul: "Penerangan jalan minim di Tiban",
    deskripsi: "Sudah lama lampu jalan rusak, belum diperbaiki juga.",
    cuaca: "cerah",
    kerusakan: "40%",
    lokasi: "Tiban Baru, Kec. Sekupang, Kota Batam, Kepulauan Riau 29424",
    status: "selesai",
  },
  {
    id: "8",
    tanggal: "2024-08-09",
    judul: "Lubang besar di jalan Batu Besar",
    deskripsi: "Lubangnya besar banget, kayak jebakan Batman.",
    cuaca: "hujan",
    kerusakan: "60%",
    lokasi: "Jl. Hang Nadim, Belian, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29465",
    status: "selesai",
  },
  {
    id: "9",
    tanggal: "2025-03-30",
    judul: "Jalan Nongsa banyak tambalan",
    deskripsi: "Kenapa tambal sulam terus? Tolong kerja yang bener dong.",
    cuaca: "cerah",
    kerusakan: "60%",
    lokasi: "Jl. Letjend Suprapto, Tembesi, Kec. Sagulung, Kota Batam",
    status: "disembunyikan",
  },
  {
    id: "10",
    tanggal: "2025-02-14",
    judul: "Batam masih saja gelap gulita tiap malam",
    deskripsi: "Gara-gara lampu jalan mati terus, banyak yang jadi korban.",
    cuaca: "hujan",
    kerusakan: "80%",
    lokasi: "Tlk. Tering, Kec. Batam Kota, Kota Batam",
    status: "selesai",
  },
  {
    id: "11",
    tanggal: "2024-04-11",
    judul: "Sampah menumpuk di area pasar Aviari",
    deskripsi: "Sampah sudah kayak gunung, mana petugas kebersihan?",
    cuaca: "cerah",
    kerusakan: "20%",
    lokasi: "Buliang, Kec. Batu Aji, Kota Batam, Kepulauan Riau 29425",
    status: "selesai",
  },
  {
    id: "12",
    tanggal: "2024-09-05",
    judul: "Banjir di depan Polsek Batu Aji",
    deskripsi: "Polisi lihat banjir juga nggak peduli, cuma bengong.",
    cuaca: "hujan",
    kerusakan: "100%",
    lokasi: "Jl. Brigjen Katamso, Tj. Uncang, Kec. Batu Aji, Kota Batam, Kepulauan Riau 29438",
    status: "disembunyikan",
  },
  {
    id: "13",
    tanggal: "2025-05-10",
    judul: "Lampu lalu lintas tidak berfungsi",
    deskripsi: "Sudah sebulan lebih lampu lalu lintas di Simpang KDA mati.",
    cuaca: "cerah",
    kerusakan: "60%",
    lokasi: "2XVH+J2R, Jl. Letjen R. Suprapto, Sungai Langkai, Kec. Sagulung, Kota Batam, Kepulauan Riau 29424",
    status: "selesai",
  },
  {
    id: "14",
    tanggal: "2024-06-18",
    judul: "Trotoar rusak di Batamkota",
    deskripsi: "Trotoar berlubang dan berbahaya untuk anak sekolah.",
    cuaca: "cerah",
    kerusakan: "40%",
    lokasi: "Jl. Engku Putri Utara 1, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444",
    status: "selesai",
  },
  {
    id: "15",
    tanggal: "2025-03-02",
    judul: "Akses ke jembatan Barelang penuh lubang",
    deskripsi: "Jalan ke Barelang kayak jalur offroad, parah betul!",
    cuaca: "hujan",
    kerusakan: "80%",
    lokasi: "Jl. Letjend Suprapto, Kibing, Kec. Batu Aji, Kota Batam, Kepulauan Riau 29424",
    status: "selesai",
  },
  {
    id: "16",
    tanggal: "2024-10-12",
    judul: "Warga resah dengan bau menyengat",
    deskripsi: "Entah dari mana bau ini, tapi siapa pun pemerintahnya, tolong lah kerja!",
    cuaca: "cerah",
    kerusakan: "20%",
    lokasi: "Tembesi, Kec. Sagulung, Kota Batam, Kepulauan Riau 29424",
    status: "disembunyikan",
  },
  {
    id: "17",
    tanggal: "2025-04-07",
    judul: "Parit mampet di Sagulung",
    deskripsi: "Air nggak ngalir, parit kayak kolam ikan.",
    cuaca: "hujan",
    kerusakan: "60%",
    lokasi: "Kibing, Kec. Batu Aji, Kota Batam, Kepulauan Riau 29424",
    status: "selesai",
  },
  {
    id: "18",
    tanggal: "2024-05-22",
    judul: "Jalan baru tapi sudah rusak",
    deskripsi: "Baru dibangun sudah berlubang. Yang bangun tolol atau gimana?",
    cuaca: "hujan",
    kerusakan: "40%",
    lokasi: "32VP+R7J, Jl. Ahmad Yani, Sukajadi, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29433",
    status: "disembunyikan",
  },
  {
    id: "19",
    tanggal: "2024-03-11",
    judul: "Tidak ada tindakan untuk jalan rusak",
    deskripsi: "Laporkan berkali-kali, tetap saja tidak diperbaiki.",
    cuaca: "cerah",
    kerusakan: "60%",
    lokasi: "32VP+R7J, Jl. Ahmad Yani, Sukajadi, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29433",
    status: "selesai",
  },
  {
    id: "20",
    tanggal: "2025-05-01",
    judul: "Penerangan minim di Dapur 12",
    deskripsi: "Sudah gelap, jalan rusak, terus siapa yang peduli?",
    cuaca: "hujan",
    kerusakan: "80%",
    lokasi: "Jl. Kav. Flamboyan 2, Sungai Pelunggut, Kec. Sagulung, Kota Batam, Kepulauan Riau 29425",
    status: "selesai",
  },
  {
    id: "21",
    tanggal: "2024-11-20",
    judul: "Banjir parah di kawasan Industri Tunas",
    deskripsi: "Setiap hujan pasti banjir, politisi Batam cuma mikir kampanye.",
    cuaca: "hujan",
    kerusakan: "100%",
    lokasi: "32VP+R7J, Jl. Ahmad Yani, Sukajadi, Kec. Batam Kota, Kota Batam",
    status: "disembunyikan",
  },
  {
    id: "22",
    tanggal: "2025-01-25",
    judul: "Jalan utama Sagulung bergelombang",
    deskripsi: "Sulit dilalui kendaraan roda dua.",
    cuaca: "cerah",
    kerusakan: "60%",
    lokasi: "Tembesi, Kec. Sagulung, Kota Batam, Kepulauan Riau 29424",
    status: "selesai",
  },
  {
    id: "23",
    tanggal: "2024-12-18",
    judul: "Lampu taman tidak menyala",
    deskripsi: "Sudah lama rusak tapi nggak ada perhatian.",
    cuaca: "cerah",
    kerusakan: "40%",
    lokasi: "Jl. Komp. Sakura Anpan, Lubuk Baja Kota, Kec. Lubuk Baja, Kota Batam",
    status: "selesai",
  },
  {
    id: "24",
    tanggal: "2025-03-18",
    judul: "Gorong-gorong mampet di Batu Aji",
    deskripsi: "Kalau gorong-gorong mampet terus, jangan salahin warga kalau marah.",
    cuaca: "hujan",
    kerusakan: "60%",
    lokasi: "",
    status: "disembunyikan",
  },
  {
    id: "25",
    tanggal: "2024-09-27",
    judul: "Aspal mengelupas di jalan engku putri",
    deskripsi: "Sudah kayak jalanan zaman dulu, kapan diaspal ulang?",
    cuaca: "cerah",
    kerusakan: "40%",
    lokasi: "Jl. Raja H. Fisabilillah No.1, Tlk. Tering, Kec. Batam Kota, Kota Batam",
    status: "selesai",
  },
  {
    id: "26",
    tanggal: "2025-02-05",
    judul: "Pipa air bocor di Bengkong",
    deskripsi: "Sudah lama air mengalir terus, tapi tidak ditangani.",
    cuaca: "hujan",
    kerusakan: "20%",
    lokasi: "Jl. Golden Prawn 56, Tj. Buntung, Kec. Bengkong, Kota Batam, Kepulauan Riau 29444",
    status: "selesai",
  },
  {
    id: "27",
    tanggal: "2025-04-12",
    judul: "Kabel menjuntai berbahaya di Nagoya",
    deskripsi: "Anak-anak bisa kena sengatan listrik, tolong segera dibenahi.",
    cuaca: "cerah",
    kerusakan: "60%",
    lokasi: "Jl. Komp. Sakura Anpan, Lubuk Baja Kota, Kec. Lubuk Baja, Kota Batam",
    status: "selesai",
  },
  {
    id: "28",
    tanggal: "2024-08-16",
    judul: "Jalan didepan perumahan Cendana rusak berat",
    deskripsi: "Sudah kayak kubangan kerbau.",
    cuaca: "hujan",
    kerusakan: "100%",
    lokasi: "32VP+R7J, Jl. Ahmad Yani, Sukajadi, Kec. Batam Kota, Kota Batam",
    status: "selesai",
  },
  {
    id: "29",
    tanggal: "2024-07-03",
    judul: "Jembatan penyebrangan di deket STM goyang bro",
    deskripsi: "Tiap lewat jembatan ini nyawa serasa terbang.",
    cuaca: "cerah",
    kerusakan: "80%",
    lokasi: "Kibing, Kec. Batu Aji, Kota Batam, Kepulauan Riau 29424",
    status: "selesai",
  },
  {
    id: "30",
    tanggal: "2025-03-07",
    judul: "Batam penuh janji politik",
    deskripsi: "Katanya infrastruktur dibenahi, kenyataannya zonk. Pemimpin mana?",
    cuaca: "cerah",
    kerusakan: "60%",
    lokasi: "Jl. Ahmad Yani, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29461",
    status: "disembunyikan",
  },
  ];
};

const RecommendedPage = async () => {
  const data = await getData();
  return (
    <div className="">
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">Data Laporan</h1>
      </div>
      <DataTable columns={columns} data={data}/>
    </div>
  );
};

export default RecommendedPage;