import { Recommended, columns } from "../../../components/data_laporan/columns";
import { DataTable } from "../../../components/data_laporan/data-table";

const getData = async (): Promise<Recommended[]> => {
  return [
    {
      id: "1",
      tanggal: "2024-02-15",
      judul: "Jalan depan SP Batu Aji rusak parah",
      jenisInfrastruktur: "jembatan",
      cuaca: "hujan",
      kerusakan: "80%",
      lokasi: "Jl. Letjend Suprapto, Tembesi, Kec. Sagulung, Kota Batam",
      status: "selesai",
    },
    {
      id: "2",
      tanggal: "2024-03-20",
      judul: "Perbaikan jalan di Batam lambat banget",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "60%",
      lokasi: "Jl. Letjend Suprapto, Tembesi, Kec. Sagulung, Kota Batam",
      status: "disembunyikan",
    },
    {
      id: "3",
      tanggal: "2024-11-03",
      judul: "Lampu jalan padam di Bengkong",
      jenisInfrastruktur: "jembatan",
      cuaca: "cerah",
      kerusakan: "40%",
      lokasi:
        "Jl. Golden Prawn 56, Tj. Buntung, Kec. Bengkong, Kota Batam, Kepulauan Riau 29444",
      status: "selesai",
    },
    {
      id: "4",
      tanggal: "2025-01-10",
      judul: "Trotoar rusak dan tidak layak di Batam Center",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "60%",
      lokasi: "Tlk. Tering, Kec. Batam Kota, Kota Batam",
      status: "selesai",
    },
    {
      id: "5",
      tanggal: "2025-04-21",
      judul: "Ada yang mencuri besi jembatan di Sei Beduk",
      jenisInfrastruktur: "jembatan",
      cuaca: "hujan",
      kerusakan: "100%",
      lokasi:
        "Jl. Diponegoro, Tj. Riau, Kec. Sekupang, Kota Batam, Kepulauan Riau 29424",
      status: "disembunyikan",
    },
    {
      id: "6",
      tanggal: "2024-12-05",
      judul: "Genangan air di jalan utama Batam",
      jenisInfrastruktur: "jalan",
      cuaca: "hujan",
      kerusakan: "80%",
      lokasi: "Jl. Letjend Suprapto, Tembesi, Kec. Sagulung, Kota Batam",
      status: "disembunyikan",
    },
    {
      id: "7",
      tanggal: "2024-07-19",
      judul: "Penerangan jalan minim di Tiban",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "40%",
      lokasi: "Tiban Baru, Kec. Sekupang, Kota Batam, Kepulauan Riau 29424",
      status: "selesai",
    },
    {
      id: "8",
      tanggal: "2024-08-09",
      judul: "Lubang besar di jalan Batu Besar",
      jenisInfrastruktur: "lampu_jalan",
      cuaca: "hujan",
      kerusakan: "60%",
      lokasi:
        "Jl. Hang Nadim, Belian, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29465",
      status: "selesai",
    },
    {
      id: "9",
      tanggal: "2025-03-30",
      judul: "Jalan Nongsa banyak tambalan",
      jenisInfrastruktur: "lampu_jalan",
      cuaca: "cerah",
      kerusakan: "60%",
      lokasi: "Jl. Letjend Suprapto, Tembesi, Kec. Sagulung, Kota Batam",
      status: "disembunyikan",
    },
    {
      id: "10",
      tanggal: "2025-02-14",
      judul: "Batam masih saja gelap gulita tiap malam",
      jenisInfrastruktur: "lampu_jalan",
      cuaca: "hujan",
      kerusakan: "80%",
      lokasi: "Tlk. Tering, Kec. Batam Kota, Kota Batam",
      status: "selesai",
    },
    {
      id: "11",
      tanggal: "2024-04-11",
      judul: "Sampah menumpuk di area pasar Aviari",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "20%",
      lokasi: "Buliang, Kec. Batu Aji, Kota Batam, Kepulauan Riau 29425",
      status: "selesai",
    },
    {
      id: "12",
      tanggal: "2024-09-05",
      judul: "Banjir di depan Polsek Batu Aji",
      jenisInfrastruktur: "jalan",
      cuaca: "hujan",
      kerusakan: "100%",
      lokasi:
        "Jl. Brigjen Katamso, Tj. Uncang, Kec. Batu Aji, Kota Batam, Kepulauan Riau 29438",
      status: "disembunyikan",
    },
    {
      id: "13",
      tanggal: "2025-05-10",
      judul: "Lampu lalu lintas tidak berfungsi",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "60%",
      lokasi:
        "2XVH+J2R, Jl. Letjen R. Suprapto, Sungai Langkai, Kec. Sagulung, Kota Batam, Kepulauan Riau 29424",
      status: "selesai",
    },
    {
      id: "14",
      tanggal: "2024-06-18",
      judul: "Trotoar rusak di Batamkota",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "40%",
      lokasi:
        "Jl. Engku Putri Utara 1, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29444",
      status: "selesai",
    },
    {
      id: "15",
      tanggal: "2025-03-02",
      judul: "Akses ke jembatan Barelang penuh lubang",
      jenisInfrastruktur: "jalan",
      cuaca: "hujan",
      kerusakan: "80%",
      lokasi:
        "Jl. Letjend Suprapto, Kibing, Kec. Batu Aji, Kota Batam, Kepulauan Riau 29424",
      status: "selesai",
    },
    {
      id: "16",
      tanggal: "2024-10-12",
      judul: "Warga resah dengan bau menyengat",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "20%",
      lokasi: "Tembesi, Kec. Sagulung, Kota Batam, Kepulauan Riau 29424",
      status: "disembunyikan",
    },
    {
      id: "17",
      tanggal: "2025-04-07",
      judul: "Parit mampet di Sagulung",
      jenisInfrastruktur: "jalan",
      cuaca: "hujan",
      kerusakan: "60%",
      lokasi: "Kibing, Kec. Batu Aji, Kota Batam, Kepulauan Riau 29424",
      status: "selesai",
    },
    {
      id: "18",
      tanggal: "2024-05-22",
      judul: "Jalan baru tapi sudah rusak",
      jenisInfrastruktur: "jalan",
      cuaca: "hujan",
      kerusakan: "40%",
      lokasi:
        "32VP+R7J, Jl. Ahmad Yani, Sukajadi, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29433",
      status: "disembunyikan",
    },
    {
      id: "19",
      tanggal: "2024-03-11",
      judul: "Tidak ada tindakan untuk jalan rusak",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "60%",
      lokasi:
        "32VP+R7J, Jl. Ahmad Yani, Sukajadi, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29433",
      status: "selesai",
    },
    {
      id: "20",
      tanggal: "2025-05-01",
      judul: "Penerangan minim di Dapur 12",
      jenisInfrastruktur: "jalan",
      cuaca: "hujan",
      kerusakan: "80%",
      lokasi:
        "Jl. Kav. Flamboyan 2, Sungai Pelunggut, Kec. Sagulung, Kota Batam, Kepulauan Riau 29425",
      status: "selesai",
    },
    {
      id: "21",
      tanggal: "2024-11-20",
      judul: "Banjir parah di kawasan Industri Tunas",
      jenisInfrastruktur: "jalan",
      cuaca: "hujan",
      kerusakan: "100%",
      lokasi: "32VP+R7J, Jl. Ahmad Yani, Sukajadi, Kec. Batam Kota, Kota Batam",
      status: "disembunyikan",
    },
    {
      id: "22",
      tanggal: "2025-01-25",
      judul: "Jalan utama Sagulung bergelombang",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "60%",
      lokasi: "Tembesi, Kec. Sagulung, Kota Batam, Kepulauan Riau 29424",
      status: "selesai",
    },
    {
      id: "23",
      tanggal: "2024-12-18",
      judul: "Lampu taman tidak menyala",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "40%",
      lokasi:
        "Jl. Komp. Sakura Anpan, Lubuk Baja Kota, Kec. Lubuk Baja, Kota Batam",
      status: "selesai",
    },
    {
      id: "24",
      tanggal: "2025-03-18",
      judul: "Gorong-gorong mampet di Batu Aji",
      jenisInfrastruktur: "jalan",
      cuaca: "hujan",
      kerusakan: "60%",
      lokasi: "...",
      status: "disembunyikan",
    },
    {
      id: "25",
      tanggal: "2024-09-27",
      judul: "Aspal mengelupas di jalan engku putri",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "40%",
      lokasi:
        "Jl. Raja H. Fisabilillah No.1, Tlk. Tering, Kec. Batam Kota, Kota Batam",
      status: "selesai",
    },
    {
      id: "26",
      tanggal: "2025-02-05",
      judul: "Pipa air bocor di Bengkong",
      jenisInfrastruktur: "jalan",
      cuaca: "hujan",
      kerusakan: "20%",
      lokasi:
        "Jl. Golden Prawn 56, Tj. Buntung, Kec. Bengkong, Kota Batam, Kepulauan Riau 29444",
      status: "selesai",
    },
    {
      id: "27",
      tanggal: "2025-04-12",
      judul: "Kabel menjuntai berbahaya di Nagoya",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "60%",
      lokasi:
        "Jl. Komp. Sakura Anpan, Lubuk Baja Kota, Kec. Lubuk Baja, Kota Batam",
      status: "selesai",
    },
    {
      id: "28",
      tanggal: "2024-08-16",
      judul: "Jalan didepan perumahan Cendana rusak berat",
      jenisInfrastruktur: "jalan",
      cuaca: "hujan",
      kerusakan: "100%",
      lokasi: "32VP+R7J, Jl. Ahmad Yani, Sukajadi, Kec. Batam Kota, Kota Batam",
      status: "selesai",
    },
    {
      id: "29",
      tanggal: "2024-07-03",
      judul: "Jembatan penyebrangan di deket STM goyang bro",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "80%",
      lokasi: "Kibing, Kec. Batu Aji, Kota Batam, Kepulauan Riau 29424",
      status: "selesai",
    },
    {
      id: "30",
      tanggal: "2025-03-07",
      judul: "Batam penuh janji politik",
      jenisInfrastruktur: "jalan",
      cuaca: "cerah",
      kerusakan: "60%",
      lokasi:
        "Jl. Ahmad Yani, Tlk. Tering, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29461",
      status: "disembunyikan",
    },
  ];
};

const RecommendedPage = async () => {
  const data = await getData();
  return (
    <div>
      <DataTable columns={columns} data={data} />
    </div>
  );
};

export default RecommendedPage;
