import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers"; // <- Perbaikan dari "next/header" ke "next/headers"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider"

// konfigurasi font 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BALAP-IN",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = cookies();
  const isSidebarEnabled = cookieStore.get("sidebar_state")?.value === "true";
  const pathname = ""; // <- kamu bisa pakai usePathname() dari next/navigation di client-side,
                       // atau inject dari luar kalau SSR

  const useSimpleLayout = pathname.startsWith("/login"); // contoh kondisi

   return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {useSimpleLayout ? (
            children
          ) : (
            <SidebarProvider defaultOpen={isSidebarEnabled}>
              <AppSidebar />
              <main className="p-4">
                <SidebarTrigger />
                {children}
              </main>
            </SidebarProvider>
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
export async function Layout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
 
  return (
    <SidebarProvider defaultOpen={defaultOpen}>
      <AppSidebar />
      <main>
        <SidebarTrigger />
        {children}
      </main>
    </SidebarProvider>
  )
}