import {
  Recommended,
  columns,
} from "../../../components/data_rekomendasi/columns";
import { DataTable } from "../../../components/data_rekomendasi/data-table";

const getData = async (): Promise<Recommended[]> => {
  return [
    {
      id: 1,
      judul: "Jalan berlubang besar",
      jenis: "jalan",
      alamat: "Jl. Ahmad Yani",
      cuaca: "hujan",
      status_rekom: "diproses",
      status_urgent: "80%",
      tingkat_urgent: "tinggi",
    },
    {
      id: 2,
      judul: "Lampu jalan mati total",
      jenis: "lampu_jalan",
      alamat: "Jl. Sudirman No. 12",
      cuaca: "cerah",
      status_rekom: "belum_divalidasi",
      status_urgent: "40%",
      tingkat_urgent: "rendah",
    },
    {
      id: 3,
      judul: "Retakan jalan",
      jenis: "jalan",
      alamat: "Jl. Merdeka No. 45",
      cuaca: "hujan",
      status_rekom: "divalidasi",
      status_urgent: "60%",
      tingkat_urgent: "sedang",
    },
    {
      id: 4,
      judul: "Lampu jalan tidak menyala",
      jenis: "lampu_jalan",
      alamat: "Jl. Kartini No. 5",
      cuaca: "cerah",
      status_rekom: "diproses",
      status_urgent: "20%",
      tingkat_urgent: "rendah",
    },
    {
      id: 5,
      judul: "Jalan bergelombang",
      jenis: "jalan",
      alamat: "Jl. Imam Bonjol No. 10",
      cuaca: "hujan",
      status_rekom: "divalidasi",
      status_urgent: "60%",
      tingkat_urgent: "sedang",
    },
    {
      id: 6,
      judul: "Lampu jalan rusak",
      jenis: "lampu_jalan",
      alamat: "Jl. Soekarno Hatta",
      cuaca: "cerah",
      status_rekom: "diproses",
      status_urgent: "100%",
      tingkat_urgent: "tinggi",
    },
    {
      id: 7,
      judul: "Aspal mengelupas",
      jenis: "jalan",
      alamat: "Jl. Diponegoro No. 9",
      cuaca: "hujan",
      status_rekom: "belum_divalidasi",
      status_urgent: "100%",
      tingkat_urgent: "tinggi",
    },
    {
      id: 8,
      judul: "Lampu jalan padam sebagian",
      jenis: "lampu_jalan",
      alamat: "Jl. Pelita No. 22",
      cuaca: "hujan",
      status_rekom: "diproses",
      status_urgent: "80%",
      tingkat_urgent: "tinggi",
    },
    {
      id: 9,
      judul: "Jalan rusak parah",
      jenis: "jalan",
      alamat: "Jl. Teuku Umar No. 8",
      cuaca: "cerah",
      status_rekom: "divalidasi",
      status_urgent: "100%",
      tingkat_urgent: "tinggi",
    },
    {
      id: 10,
      judul: "Lampu jalan korslet",
      jenis: "lampu_jalan",
      alamat: "Jl. Gajah Mada No. 14",
      cuaca: "hujan",
      status_rekom: "belum_divalidasi",
      status_urgent: "80%",
      tingkat_urgent: "tinggi",
    },
    {
      id: 11,
      judul: "Permukaan jalan rusak",
      jenis: "jalan",
      alamat: "Jl. Cempaka No. 1",
      cuaca: "cerah",
      status_rekom: "divalidasi",
      status_urgent: "20%",
      tingkat_urgent: "rendah",
    },
    {
      id: 12,
      judul: "Lampu jalan kedap-kedip",
      jenis: "lampu_jalan",
      alamat: "Jl. Raya Bukit Indah",
      cuaca: "hujan",
      status_rekom: "diproses",
      status_urgent: "20%",
      tingkat_urgent: "rendah",
    },
    {
      id: 13,
      judul: "Aspal retak dan berlubang",
      jenis: "jalan",
      alamat: "Jl. Bunga Mawar No. 7",
      cuaca: "cerah",
      status_rekom: "diproses",
      status_urgent: "80%",
      tingkat_urgent: "tinggi",
    },
    {
      id: 14,
      judul: "Lampu jalan jatuh",
      jenis: "lampu_jalan",
      alamat: "Jl. Pemuda No. 33",
      cuaca: "angin_kencang",
      status_rekom: "diproses",
      status_urgent: "60%",
      tingkat_urgent: "sedang",
    },
    {
      id: 15,
      judul: "Jalan berlubang kecil",
      jenis: "jalan",
      alamat: "Jl. Teratai Putih",
      cuaca: "hujan",
      status_rekom: "divalidasi",
      status_urgent: "40%",
      tingkat_urgent: "rendah",
    },
    {
      id: 16,
      judul: "Lampu jalan menyala siang hari",
      jenis: "lampu_jalan",
      alamat: "Jl. Mangga Besar",
      cuaca: "cerah",
      status_rekom: "diproses",
      status_urgent: "100%",
      tingkat_urgent: "tinggi",
    },
    {
      id: 17,
      judul: "Jalan menurun licin",
      jenis: "jalan",
      alamat: "Jl. Melati Indah",
      cuaca: "hujan",
      status_rekom: "diproses",
      status_urgent: "100%",
      tingkat_urgent: "tinggi",
    },
    {
      id: 18,
      judul: "Lampu jalan tidak stabil",
      jenis: "lampu_jalan",
      alamat: "Jl. Cemara No. 18",
      cuaca: "hujan",
      status_rekom: "belum_divalidasi",
      status_urgent: "80%",
      tingkat_urgent: "tinggi",
    },
    {
      id: 19,
      judul: "Jalan retak akibat truk berat",
      jenis: "jalan",
      alamat: "Jl. Pahlawan No. 22",
      cuaca: "cerah",
      status_rekom: "diproses",
      status_urgent: "40%",
      tingkat_urgent: "rendah",
    },
    {
      id: 20,
      judul: "Jembatan berlubang di bagian tengah",
      jenis: "jembatan",
      alamat: "Jl. Rajawali No. 40",
      cuaca: "hujan",
      status_rekom: "divalidasi",
      status_urgent: "100%",
      tingkat_urgent: "tinggi",
    },
  ];
};

const RecommendedPage = async () => {
  const data = await getData();
  return (
    <>
      <DataTable columns={columns} data={data} />
    </>
  );
};

export default RecommendedPage;
